### ISSUE TITLE
Affinity Designer: Strokes widths are wrong

### ISSUE THREAD

**Issue by hpohlmeyer** [bjango/Greyprint#1]
If you apply a stroke style in Affinity Designer, it is not 1pt/2pt/3pt.
Instead of a real stroke, a stroke effect is added. The stroke effect is measured in px instead of pt, which makes it dependent on the ppi setting of the document.

I tried to fix it by creating styles with real strokes, which are 1pt in size, but AD does not let you add styles that only differ in the stroke alignment.

I opened a [bug report](https://affinity.serif.com/forum/index.php?/topic/25641-unable-to-create-styles-for-strokes-with-different-alignment/) for that in the Serif forums.

**Comment by hpohlmeyer** [comment]
The bug got acknowledged by the AD developers.

**Comment by marcedwards** [comment]
@hpohlmeyer Thanks! I’m happy to change to whatever method is best. I’ll investigate switching to using vector stroke rather than the outline layer effect. I think that would be best?

**Comment by marcedwards** [comment]
@hpohlmeyer I attempted to switch to vector stroke rather than the outline layer effect, and I couldn't save separate styles for 1pt centre stroke and 1pt inside stroke. It seems that maybe Affinity Designer considers them to be identical and it won’t let me save the new style. Any ideas?

I’ve updated the effect strokes to at least be the correct size.

**Comment by hpohlmeyer** [comment]
@marcedwards I tried that too and hit the same problem.
The developers are aware of this, but I think it will have a pretty low priority on their list.

The only ideas I can come up with are:
1. adjusting the stroke effect like you allready did
2. using a slightly lighter color (e.g. #010101) for the inside strokes.

**Comment by badcat** [comment]
Hi - I'd consider using the Object stroke too instead of the Layer Effects. I'm not seeing a bug when saving Styles with strokes larger than 1pt. Plus by using real object stroke, the stroke stays at size even after resizing the object, no?  

@marcedwards I recreated your Stroke styles with object strokes (also shortening the names slightly so they read in the Affininty Designer icon view)  Do these work?  Or am I missing something?
- 1p-In  =  1pt Inside
- 2p-In  =  2pt Inside
- 3p-In  =  3pt Inside
- 1p-Cn  =  1pt Center
- 2p-Cn  =  2pt Center
- 3p-Cn  =  3pt Center
- 2p-Cn-%  =  2pt Center Scale Stroke  (An example - The other strokes do not scale by default)

All this was made with Affinity Designer 1.4.3

thanks for Greyprint!
[Greyprint Styles-v2.zip](https://github.com/bjango/Greyprint/files/511489/Greyprint.Styles-v2.zip)

**Comment by hpohlmeyer** [comment]
@badcat Your strokes have different colors.

Center strokes: #000000
Inside strokes: #231F20

That’s why you don’t have a problem creating the inside strokes.

The stroke widths don’t match either for me:
1pt = 4,2pt
2pt = 8,3pt
3pt = 12,5pt

**Comment by badcat** [comment]
@hpohlmeyer Ah so.. they do have different colors.  Corrected ? in this version attached.

I didn't think the color had anything to do with the stroke creation though.

However I do see the stoke width issue - it's because we're not creating with the same measurement system of course :)  All mine are in POINTS (pt)  and not PIXELS (px).  Since my setup was with a 300DPI document the **Point** size is different than a 72DPI document.

I guess the issue should be that Affinity Designer should have some sort of relative /conversion in scaling and certainly some way to measure in PX (not PT) if your document is in fact, Pixels. :(

[Greyprint Styles-v3.zip](https://github.com/bjango/Greyprint/files/511640/Greyprint.Styles-v3.zip)

**Comment by hpohlmeyer** [comment]
@badcat Ah, you are right, that is too bad …

So you really got to use a predefined document to work with these styles.
The ppi setting and your stroke styles have to line up perfectly.

That renders stroke styles pretty much useless, if you work with different ppi settings all the time.

The problem here is, that Affinity uses the DTP-point, which is ~0,35mm, not the abstract point unit of ui design. So this is the right behavior of Affinity. It would be nice if they would add another unit for ui points.

**Comment by marcedwards** [comment]
Sticking to exact multiples of 72 should solve the points to pixels issue for UI scale? As long as we can eventually use vector strokes in points, it should all be good? (Well, as good as Illustrator and Photoshop, anyway?)

I just attempted to HEX edit my way around the issue of not being able to save the styles with the same stroke weight, with no luck. Oh well, it was worth a shot.

**Comment by badcat** [comment]
So here's a tip / disclaimer... Assuming Greyprint would be geared primarily towards UI / UX / screen based design, then the unit of measure would be PX not PT. Correctly setting up the environment in PX beforehand would solve the issue in most situations.  See this:
https://twitter.com/MacAffinity/status/784292638392328192

And with that, here's the revised style (created with AD 1.5) with the correct stroke widths in PX. What's interesting is that since these were now built by default using PX, they seem to convert nicely to PT if the doc is set up as PT rather than PX.  Take a look.
[Greyprint Styles-v4.zip](https://github.com/bjango/Greyprint/files/516195/Greyprint.Styles-v4.zip)

**Comment by marcedwards** [comment]
> @badcat Assuming Greyprint would be geared primarily towards UI / UX / screen based design, then the unit of measure would be PX not PT.

Points should be safe to use in Affinity Designer for UI and screen based design, provided the correct document DPI is set (72DPI in most cases, 144DPI if working at 2× UI scale).

Points should map better to iOS points, CSS px (which behave like points and don’t always correlate to screen pixels), Android dp, macOS points etc.

I agree about the style names. I kept them the same as the other styles for other tools, but that’s not ideal for Affinity Designer. I’ll make the names small enough to fit in the panel.

**Comment by marcedwards** [comment]
I’ve updated the repo to use vector strokes in points, and I'm using `rgb(0, 0, 1)` for the colour on the inside strokes, so they save. I’ve also used `Stroke 1pt` for the centred strokes and `Inside 1pt` for the inside strokes, so the names fit better.

Thanks for the feedback! Hopefully that’s better?

**Comment by marcedwards** [comment]
@hpohlmeyer Thank you for starting this issue. Hopefully the current repo is good, and solves this issue as well as can be done right now. I am going to close this issue for now, but feel free to open another one if further action needs to be taken.

@badcat Thanks for your input as well!
